In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df = pd.read_csv("Resources/cancerpatientdata.csv")

# Review the DataFrame
df.head()

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,P1,33,1,2,4,5,4,3,2,2,...,3,4,2,2,3,1,2,3,4,Low
1,P10,17,1,3,1,5,3,4,2,2,...,1,3,7,8,6,2,1,7,2,Medium
2,P100,35,1,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,High
3,P1000,37,1,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,High
4,P101,46,1,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,High

In [30]:
# df2 = df.replace({'Level': 'Low', 'Level': 'Medium', 'Level': 'High'},
# {'Level': 1, 'Level': 2, 'Level': 3}, regex=True)
# df2 = df.replace('Medium','2', regex=True)
# df2 = df.replace('High','3', regex=True)
df['Level'] = df['Level'].replace(['Low', 'Medium', 'High'], [1, 2, 3])
df

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,P1,33,1,2,4,5,4,3,2,2,...,3,4,2,2,3,1,2,3,4,1
1,P10,17,1,3,1,5,3,4,2,2,...,1,3,7,8,6,2,1,7,2,2
2,P100,35,1,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3
3,P1000,37,1,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,3
4,P101,46,1,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,P995,44,1,6,7,7,7,7,6,7,...,5,3,2,7,8,2,4,5,3,3
996,P996,37,2,6,8,7,7,7,6,7,...,9,6,5,7,2,4,3,1,4,3
997,P997,25,2,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3
998,P998,18,2,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,3
999,P999,47,1,6,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3

In [31]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = df.Level

# Separate the X variable, the features
X = df.drop(columns='Level')
X = df.drop(columns='Patient Id')

In [32]:
# Review the y variable Series
y.head()

0    1
1    2
2    3
3    3
4    3
Name: Level, dtype: int64

In [33]:
# Review the X variable DataFrame
X.head()

,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Level
0,33,1,2,4,5,4,3,2,2,4,...,3,4,2,2,3,1,2,3,4,1
1,17,1,3,1,5,3,4,2,2,2,...,1,3,7,8,6,2,1,7,2,2
2,35,1,4,5,6,5,5,4,6,7,...,8,7,9,2,1,4,6,7,2,3
3,37,1,7,7,7,7,6,7,7,7,...,4,2,3,1,4,5,6,7,5,3
4,46,1,6,8,7,7,7,6,7,7,...,3,2,4,1,4,2,4,2,3,3

In [34]:
# Check the balance of our target values
y.value_counts()

3    365
2    332
1    303
Name: Level, dtype: int64

In [35]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [36]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
classifier = LogisticRegression(random_state=1)
classifier

# Fit the model using training data
classifier.fit(X_train, y_train)

/Users/damilolashobo/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=1)

In [37]:
 # Score the model
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.984

In [38]:
 # Predict outcomes for test data set
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test})

     Prediction  Actual
507           2       2
818           1       1
452           1       2
368           1       1
242           3       3
..          ...     ...
385           1       1
890           3       3
439           3       3
135           2       2
567           2       2

[250 rows x 2 columns]

In [39]:
 from sklearn.metrics import accuracy_score
# Display the accuracy score for the test dataset.
accuracy_score(y_test, predictions)

0.984

In [40]:
# Generate a confusion matrix for the model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

array([[78,  0,  0],
       [ 4, 74,  0],
       [ 0,  0, 94]])

In [41]:
# Print the classification report for the model
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.95      1.00      0.97        78
           2       1.00      0.95      0.97        78
           3       1.00      1.00      1.00        94

    accuracy                           0.98       250
   macro avg       0.98      0.98      0.98       250
weighted avg       0.98      0.98      0.98       250

In [42]:
y_train.value_counts()

3    271
2    254
1    225
Name: Level, dtype: int64

In [43]:
# Count the distinct values of the resampled labels data
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_train,y_train)

In [44]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
classifier1 = LogisticRegression(random_state=1)
classifier1

# Fit the model using the resampled training data
classifier1.fit(X_resampled, y_resampled)

 # Score the model
print(f"Training Data Score: {classifier1.score(X_resampled, y_resampled)}")
print(f"Testing Data Score: {classifier1.score(X_test, y_test)}")

# Make a prediction using the testing data
predictions = classifier1.predict(X_resampled)
pd.DataFrame({"Prediction": predictions, "Actual": y_resampled})

Training Data Score: 1.0
Testing Data Score: 0.988

/Users/damilolashobo/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

     Prediction  Actual
0             2       2
1             1       1
2             1       1
3             3       3
4             3       3
..          ...     ...
808           2       2
809           2       2
810           2       2
811           2       2
812           2       2

[813 rows x 2 columns]

In [45]:
# Print the balanced_accuracy score of the model 
accuracy_score(y_resampled, predictions)

1.0

In [46]:
# Generate a confusion matrix for the model
confusion_matrix(y_resampled, predictions)

array([[271,   0,   0],
       [  0, 271,   0],
       [  0,   0, 271]])

In [47]:
# Print the classification report for the model
print(classification_report(y_resampled, predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       271
           2       1.00      1.00      1.00       271
           3       1.00      1.00      1.00       271

    accuracy                           1.00       813
   macro avg       1.00      1.00      1.00       813
weighted avg       1.00      1.00      1.00       813